---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: taclib-controller-sa
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: taclib-pod-controller
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: taclib-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: taclib-controller-sa
  namespace: default
roleRef:
  kind: Role
  name: taclib-pod-controller
  apiGroup: rbac.authorization.k8s.io

