image: "python:3.7-alpine"
retry_host_sensitive: true
requirements: {}
environment: {}
resources: {}
pod_spec: {}
job_spec: {}
container_spec:
    image_pull_policy: "IfNotPresent"
init_timeout: 300
request_log_timeout: 300
namespaces:
    default: default
    significant: false
